export const ui = {
  nav: {
    home: "Home",
    about: "About",
    services: "Services",
    process: "Creative Process",
    production: "Production",
    experiences: "Brand Experiences",
    tribe: "Tribe",
    work: "Our Work",
    community: "Community",
    clients: "Clients",
    contact: "Contact",
  },
  home: {
    featuredWork: "Featured Work",
    whatWeDo: "What We Do",
    viewAllWork: "View all work",
    heroHeading: "Creativity, Overflowing.",
    heroSubtext:
      "A boutique creative communication consultancy and content creation agency — rooted in Sudan, working across the globe.",
    ctaWork: "See our work",
    ctaContact: "Start a project",
  },
  work: {
    theChallenge: "The Challenge",
    theSolution: "The Solution",
    theResults: "The Results",
    viewProject: "View project",
    client: "Client",
    results: "Results",
    backToWork: "Back to all work",
    emptyTitle: "More work coming soon",
    emptyBody: "We're crafting new stories. Check back shortly.",
  },
  contact: {
    title: "Let's make something",
    subtitle: "Tell us about your project.",
    name: "Your name",
    namePlaceholder: "Jane Doe",
    email: "Email address",
    emailPlaceholder: "jane@example.com",
    message: "Message",
    messagePlaceholder: "What can we create together?",
    send: "Send message",
    sending: "Sending\u2026",
    success: "Thanks \u2014 we'll be in touch shortly.",
    error: "Something went wrong. Please try again.",
    phone: "Phone",
    website: "Website",
    instagram: "Instagram",
    tiktok: "TikTok",
    emailLabel: "Email",
  },
  footer: {
    rights: "All rights reserved.",
    tagline: "Creativity, Overflowing.",
  },
  common: {
    loading: "Loading\u2026",
    notFound: "Page not found",
    notFoundBody: "The page you're looking for doesn't exist or has moved.",
    back: "Back",
    backHome: "Back to home",
  },
  admin: {
    navOverview: "Overview",
    navCaseStudies: "Case Studies",
    navProjects: "Projects",
    navMedia: "Media",
    navServices: "Services",
    navProcess: "Process",
    navTribe: "Tribe",
    navClients: "Clients",
    navTestimonials: "Testimonials",
    navBranding: "Branding",
    navContent: "Content",
    navContact: "Contact",
    navUsers: "Users",
    signOut: "Sign out",
  },
} as const;

export type Ui = typeof ui;

export const navItems: ReadonlyArray<{ readonly href: string; readonly label: string }> = [
  { href: "/", label: ui.nav.home },
  { href: "/about", label: ui.nav.about },
  { href: "/services", label: ui.nav.services },
  { href: "/work", label: ui.nav.work },
  { href: "/tribe", label: ui.nav.tribe },
  { href: "/clients", label: ui.nav.clients },
  { href: "/contact", label: ui.nav.contact },
];
